version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./.env:/.env
    environment:
      - "POSTGRES_PASSWORD=thereisnospoon"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "./init.sh"]
    environment:
      - "DJANGO_SETTINGS_MODULE=rucio_opint_backend.apps.core.settings"
      - "PYTHONPATH=/code:${PYTHONPATH}"
      - "ADMIN_PASSWORD=thereisnospoon"
      - "API_KEY=eyJrIjoiTDJjdUpDRHdrbFRZMGd2MlJhWmV0R3dzeldmTVlRbzciLCJuIjoidGVzdF9jZWRyaWMiLCJpZCI6MTd9"
      - "POSTGRES_DB_DEV=postgres"
      - "POSTGRES_USER_DEV=postgres"
      - "POSTGRES_PASSWORD_DEV=thereisnospoon"
      - "MODE=dev"
    volumes:
      - .:/code
    privileged: true
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db